### PR TITLE
minecart_command_block.png

### PR DESCRIPTION
**Pull request by Aroukar**
minecart_command_block
Not entire sure how this works, but I am eager to help.

### CODE REVIEW

**Comment by ZeroLevels** [comment]
You're close.  The easiest way to contribute is by forking the repository on the site, which you've done.  Then, when it's all forked, you'll need the **Github Client** for either [Windows](http://windows.github.com/) or [Mac](http://mac.github.com/).

Once you have those, you'll want to go to your repository (on the site) and clone it to your desktop, which the client will handle.  You can open the location of the repository from the client.  Once you've found all of it, you can begin to make changes/additions/and the like, whether it be adding files to folders or changing lines in text files.  Keep an eye on the client as you make changes.  It'll show you all the changes you've made to which files.  Once you're sure things are in order and satisfied with the changes, you "commit" them, which you'll give a name.  Once you've committed the changes, your last step on the client is to sync the changes between your computer and the repository on the site.  Just click the **Sync** button.

Lastly (once syncing has finished), you come back to the site, view the commit, and submit the commit itself as a pull request.  This will compare your fork of the repository to the original, allow you to give a brief description and name to the pull request, and notify the original repository owner.  Your job at that point is done.  You simply wait for the pull request to be accepted or denied.

Unfortunately, this pull request has no changes to the files within the repository itself, so cannot be accepted.  I will however fix it up myself and not your contribution within the commit itself.  Thank you very kindly for the attempt!  That is a very nice texture.  Don't give up!  If you make anything else, please make another attempt at using the Github.  It really is quite useful and easy once you get used to it.  :)

**Comment by Aroukar** [comment]
Alright.  Will do.

**Comment by Aroukar** [comment]
I'm having issues with the GitHub client, is there some kind of alternate
arrangement we can work out?

**Comment by Aroukar** [comment]
Here's my idea for dispenser_front_vertical.png

http://img208.imageshack.us/img208/1796/1i5i.png

**Pull request closed without merging**
